// Central service exports by feature. Keeps legacy import path compatibility while colocating
// implementations under lib/services/feats.
export { MaterialService } from './services/feats/materials/material-service'
export { BrigadaService } from './services/feats/brigade/brigada-service'
export { TrabajadorService } from './services/feats/worker/trabajador-service'
export { ReporteService } from './services/feats/reports/reporte-service'
export { ClienteService } from './services/feats/customer/cliente-service'
export { AtencionClienteService } from './services/feats/customer-service/atencion-cliente-service'
export { ContactoService } from './services/feats/contactos/contacto-service'
export { OfertaService } from './services/feats/ofertas/oferta-service'
export { LeadService } from './services/feats/leads/lead-service'
export { OrdenTrabajoService } from './services/feats/ordenes-trabajo/orden-trabajo-service'
export { RecursosHumanosService } from './services/feats/recursos-humanos/recursos-humanos-service'
export { IngresoMensualService } from './services/feats/recursos-humanos/ingreso-mensual-service'
export { BlogService } from './services/feats/blog/blog-service'
export { GaleriaWebService } from './services/feats/galeriaweb/galeriaweb-service'
export { MarcaService } from './services/feats/marcas/marca-service'
export { ServicioService } from './services/feats/servicios/servicio-service'
export { OfertaPersonalizadaService } from './services/feats/ofertas-personalizadas/oferta-personalizada-service'
